// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"api/config"
	"api/infrastructure/database"
	"api/interface/controller"
	"api/interface/gateway"
	"api/usecase/interactor"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeControllers(db database.Connection, table string, jc *config.JWTConfig) *controller.AppController {
	registerUserRepository := gateway.NewRegisterUserGateway(db, table)
	registerUserInteractor := interactor.NewRegisterUserInteractor(registerUserRepository)
	registerUserController := controller.NewRegisterUserController(registerUserInteractor)
	loginAuthenticationRepository := gateway.NewLoginAuthenticationGateway(db, table)
	loginAuthenticationInteractor := interactor.NewLoginAuthenticationInteractor(loginAuthenticationRepository, jc)
	loginAuthenticationController := controller.NewLoginAuthenticationController(loginAuthenticationInteractor)
	logoutController := controller.NewLogoutController()
	userAuthenticationRepository := gateway.NewUserAuthenticationGateway(db, table)
	userAuthenticationInteractor := interactor.NewUserAuthenticationInteractor(userAuthenticationRepository, jc)
	userAuthenticationController := controller.NewUserAuthenticationController(userAuthenticationInteractor)
	healthCheckController := controller.NewHealthCheckController(db)
	appController := controller.NewControllers(registerUserController, loginAuthenticationController, logoutController, userAuthenticationController, healthCheckController)
	return appController
}

// wire.go:

var controllerSet = wire.NewSet(controller.NewControllers, controller.NewRegisterUserController, controller.NewLoginAuthenticationController, controller.NewLogoutController, controller.NewUserAuthenticationController, controller.NewHealthCheckController)

var interactorSet = wire.NewSet(interactor.NewRegisterUserInteractor, interactor.NewLoginAuthenticationInteractor, interactor.NewUserAuthenticationInteractor)

var gatewaySet = wire.NewSet(gateway.NewRegisterUserGateway, gateway.NewLoginAuthenticationGateway, gateway.NewUserAuthenticationGateway)
