// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"api/config"
	"api/infrastructure/database"
	"api/interface/controller"
	"api/interface/gateway"
	"api/usecase/interactor"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeControllers(db database.Connection, jc *config.JWTConfig) *controller.AppController {
	registerUserRepository := gateway.NewRegisterUserGateway(db)
	registerUserInteractor := interactor.NewRegisterUserInteractor(registerUserRepository)
	registerUserController := controller.NewRegisterUserController(registerUserInteractor)
	loginAuthenticationRepository := gateway.NewLoginAuthenticationGateway(db)
	loginAuthenticationInteractor := interactor.NewLoginAuthenticationInteractor(loginAuthenticationRepository, jc)
	loginAuthenticationController := controller.NewLoginAuthenticationController(loginAuthenticationInteractor)
	logoutController := controller.NewLogoutController()
	userAuthenticationRepository := gateway.NewUserAuthenticationGateway(db)
	userAuthenticationInteractor := interactor.NewUserAuthenticationInteractor(userAuthenticationRepository, jc)
	userAuthenticationController := controller.NewUserAuthenticationController(userAuthenticationInteractor)
	forgotRepository := gateway.NewForgotGateway(db)
	forgotInteractor := interactor.NewForgotInteractor(forgotRepository)
	forgotController := controller.NewForgotController(forgotInteractor)
	resetRepository := gateway.NewResetGateway(db)
	resetInteractor := interactor.NewResetInteractor(resetRepository)
	resetController := controller.NewResetController(resetInteractor)
	healthCheckController := controller.NewHealthCheckController(db)
	appController := controller.NewControllers(registerUserController, loginAuthenticationController, logoutController, userAuthenticationController, forgotController, resetController, healthCheckController)
	return appController
}

// wire.go:

var controllerSet = wire.NewSet(controller.NewControllers, controller.NewRegisterUserController, controller.NewLoginAuthenticationController, controller.NewLogoutController, controller.NewUserAuthenticationController, controller.NewForgotController, controller.NewResetController, controller.NewHealthCheckController)

var interactorSet = wire.NewSet(interactor.NewRegisterUserInteractor, interactor.NewLoginAuthenticationInteractor, interactor.NewUserAuthenticationInteractor, interactor.NewForgotInteractor, interactor.NewResetInteractor)

var gatewaySet = wire.NewSet(gateway.NewRegisterUserGateway, gateway.NewLoginAuthenticationGateway, gateway.NewUserAuthenticationGateway, gateway.NewForgotGateway, gateway.NewResetGateway)
